### ISSUE TITLE
과제 진행 간 issue 사항

### ISSUE THREAD

**Issue by ksnx3684** [ksnx3684/hanghae_level5#1]
1. 계층형 아키텍처 구조에서의 트랜잭션 처리 방안에 대한 고찰

- Sequelize를 통한 트랜잭션 처리 문법에 대해 알아 본 바로는 기본적으로 DB 쿼리문이 try catch 구문 내에 있는 상태에서 트랜잭션 코드를 구성해야 한다는 것이었습니다.  문제는 DB에 접근하는 쿼리문이 Repository에 있으며, try catch 구문은 Controller에 있다는 것이었습니다. Repository에 또 다른 try catch 구문을 만들자니, Controller와 중복이 되는 것이 걸렸고 Controller에서 트랜잭션을 구성하자니, 쿼리문을 Controller로 옮길 경우 계층형 구조를 위배하는 상황이 되버린다는 점 때문에 구현 방안을 놓고 많은 고민을 했습니다.
- 결국 try catch 구문을 새로 사용하더라도 Repository에서 처리하는 방식이 더 나은 방법이라 판단하였고 이를 기반으로 코드를 구현하였습니다.

**Comment by Yunjaejo** [comment]
병훈님 안녕하세요!
이슈 남겨주신 두가지 사항은 게더에서 대면으로 모두 피드백드렸습니다.
레벨5까지 완주하시느라 너무 고생많으셨습니다. 시간남으시면 챌린지도 도전해보세요!
